metadata.format.version = "1.1"

[versions]

# ViaVersion
viaver = "5.5.2-SNAPSHOT"

# Common provided
netty = "4.0.20.Final"
guava = "17.0"
log4j = "2.8.1"

checkerQual = "3.51.0"

# Platforms
paper = "1.16.5-R0.1-SNAPSHOT"
velocity = "3.1.1"
fabricLoader = "0.11.6"
viaProxy = "3.4.6-SNAPSHOT"

[libraries]

viaver = { group = "com.viaversion", name = "viaversion", version.ref = "viaver" }

netty = { group = "io.netty", name = "netty-all", version.ref = "netty" }
guava = { group = "com.google.guava", name = "guava", version.ref = "guava" }
log4j = { group = "org.apache.logging.log4j", name = "log4j-api", version.ref = "log4j" }

checkerQual = { group = "org.checkerframework", name = "checker-qual", version.ref = "checkerQual" }

paper = { group = "com.destroystokyo.paper", name = "paper-api", version.ref = "paper" }
velocity = { group = "com.velocitypowered", name = "velocity-api", version.ref = "velocity" }
fabricLoader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabricLoader" }
viaProxy = { group = "net.raphimc", name = "ViaProxy", version.ref = "viaProxy" }
